Feature: Generate PrivateKey
  Generates a new PrivateKey instance with a random 32-byte value.

  @GROUNDED @confidence-high
  Scenario: Generate random 32-byte value
    Given a secure random generator is available
    When generate method is called
    Then a 32-byte random value should be generated
    # Source: Code line: secureRandom.nextBytes(bytes)

  @GROUNDED @confidence-high
  Scenario: Convert byte array to hexadecimal string
    Given a 32-byte random byte array is generated
    When the byte array is converted to a string
    Then the string should be a 64-character hexadecimal representation
    # Source: Code line: bytes.joinToString(separator = "") { "%02x".format(it) }

  @GROUNDED @confidence-high
  Scenario: Create PrivateKey instance from hexadecimal string
    Given a hexadecimal string is generated from a byte array
    When a PrivateKey instance is created using the string
    Then the PrivateKey instance should be valid and initialized
    # Source: Code line: return PrivateKey(bytes.joinToString(separator = "") { "%02x".format(it) })

  @INFERRED @confidence-medium
  Scenario: Ensure secureRandom generates a truly random sequence
    Given multiple calls to generate method
    When comparing generated byte arrays
    Then each byte array should be different, ensuring randomness
    # Source: Focus Areas: Verify randomness of generated byte array

  @INFERRED @confidence-low
  Scenario: Handle potential exceptions in byte array conversion
    Given an unexpected error occurs during byte array conversion
    When generate method is called
    Then an exception should be handled gracefully
    # Source: Focus Areas: Handle and test any exceptions during conversion process
