Feature: PrivateKey Generation and Conversion
  Tests for generating a private key and converting byte arrays to hex strings.

  @GROUNDED @confidence-high
  Scenario: Generate a new private key with correct byte array length
    Given a request to generate a new private key
    When the generate function is called
    Then a byte array of length 32 should be created
    # Source: Code line: val bytes = ByteArray(32)

  @GROUNDED @confidence-high
  Scenario: Convert byte array to hex string
    Given a byte array generated by the secure random
    When the byte array is converted to a hex string
    Then the hex string should represent the byte array accurately
    # Source: Code line: bytes.joinToString(separator = "") { "%02x".format(it) }

  @GROUNDED @confidence-high
  Scenario: Ensure secure random generation is functioning correctly
    Given a request to generate a new private key
    When secureRandom generates bytes for the key
    Then the generated bytes should be random
    # Source: Code line: secureRandom.nextBytes(bytes)

  @GROUNDED @confidence-high
  Scenario: Handle edge case of byte array length
    Given a request to generate a new private key
    When the byte array is created
    Then the byte array should always have a length of 32
    # Source: Code line: val bytes = ByteArray(32)
